### ISSUE TITLE
blocked by "Hoodie is already running!" after server crash

### ISSUE THREAD

**Issue by louisremi** [hoodiehq/hoodie-cli#148]
My server crashed badly, I had to destroy the VM and recreate it from the same disk. I guess this is an unusual way for Hoodie to be stopped.
Once I restored the VM, I tried to `hoodie start` but I got the "Hoodie is already running!" message. I discovered that I had to delete `data/hoodie.pid` to be able to successfully restart hoodie.

Maybe you could implement a `-f` option to avoid this kind of problem?

**Comment by fastfrwrd** [comment]
+1 to this.

**Comment by mikekuehn** [comment]
+1

**Comment by jicksy** [comment]
Faced this issue today. Deleting hoodie.pid file helped.

**Comment by janl** [comment]
Finally had time to look into this. I agree that something like an `-f` parameter would do the trick. A patch should be straightforward, as the pid utility (https://github.com/hoodiehq/hoodie-cli/blob/master/lib/hoodie/util/pid.js) already knows how to overwrite a stale pid.

Anyone up for doing this?

**Comment by christophwitzko** [comment]
@janl I created a pull request #167. :wink:
