### ISSUE TITLE
password set trough first `hoodie start` does not work when signing in to admin dashboard / futon

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-cli#157]
I've updated `hoodie-cli` to last version to make sure.

```
hoodie new test
cd test
hoodie start
# set password to 12345
```

Now open Hoodie Admin Dashboard url as seen in terminal logs and try to sign in with 12345. It doesn't work.

To workaround, set `admin=12345` in `data/couch.ini`'s `[admins]` section, then restart server.

--- 

Hoodie Cli Version: 0.6.3
node: v0.10.32
npm 2.1.14
platform: darwin
CouchDB: 1.6.1

**Comment by mikekuehn** [comment]
same problem here.  workaround?

**Comment by Heydon** [comment]
@janl I misread your workaround and typed "password" in the CLI.

My password is now "\"password"\"

Just thought that might amuse you. Any news on the pull req?

**Comment by janl** [comment]
@Heydon we are blocked on a gnarly CI issue: https://github.com/hoodiehq/hoodie-integration-test/pull/14 :/ If anyone has any insights there, we’d highly appreciate that :)

**Comment by janl** [comment]
fixed.
