### ISSUE TITLE
Hoodie Deployment - /home/hoodie/hoodie-daemon.sh not available

### ISSUE THREAD

**Issue by ronyrun** [hoodiehq/hoodie-cli#171]
Hello, 

after a regular installation on UBUNTU (http://docs.hood.ie/en/start/), the deployment informations are not usable. (http://docs.hood.ie/en/deployment/linux.html).

hoodie-daemon.sh is not available on the path communicated.

**Comment by janl** [comment]
The `hoodie-daemon.sh` script is linked in a gist from that page, you need to download it yourself, for now.
