### ISSUE TITLE
hoodie-cli install error

### ISSUE THREAD

**Issue by vickenliu** [hoodiehq/hoodie-cli#177]
Hi, i am trying to install hoodie-cli , Error: fetch failed with status code 503

my node and npm are the latest version v6.2.1 and v3.9.3

thanks.

**Comment by vickenliu** [comment]
maybe its npm server is down, cuz i also cant install other dependencies.

**Comment by varjmes** [comment]
Hi @vickenliu. You're probably all sorted now, but do let us know if you have any other issues!
